CREATE TABLE IF NOT EXISTS answers (
    answerID BIGINT(44) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    forPostID BIGINT(44) NOT NULL,
    userID BIGINT(44) NOT NULL,
    text TEXT(30000) NOT NULL,
    imageArray TEXT(150000),
    upvotes BIGINT(44) DEFAULT 0 NOT NULL,
    downvotes BIGINT(44) DEFAULT 0 NOT NULL,
    datetime VARCHAR(256) NOT NULL
);