CREATE TABLE IF NOT EXISTS nuptial_flights (
    flightID BIGINT(44) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    userID BIGINT(44) NOT NULL,
    text TEXT(30000) NOT NULL,
    imageArray TEXT(150000),
    views BIGINT(44) DEFAULT 0 NOT NULL,
    upvotes BIGINT(44) DEFAULT 0 NOT NULL,
    downvotes BIGINT(44) DEFAULT 0 NOT NULL,
    answers BIGINT(44) DEFAULT 0 NOT NULL,
    replies BIGINT(44) DEFAULT 0 NOT NULL,
    date VARCHAR(128) NOT NULL,
    time VARCHAR(128) NOT NULL,
    species VARCHAR(256) NOT NULL,
    temperature VARCHAR(50) NOT NULL,
    wind_speed VARCHAR(50) NOT NULL,
    moon_cycle VARCHAR(50) NOT NULL,
    tagOne VARCHAR(50),
    tagTwo VARCHAR(50),
    tagThree VARCHAR(50),
    tagFour VARCHAR(50),
    tagFive VARCHAR(50),
    datetime VARCHAR(256) NOT NULL,
    editedByUserID BIGINT(44) DEFAULT 0,
    editDatetime VARCHAR(256) NOT NULL
);