CREATE TABLE questions (
    questionID BIGINT(44) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    title VARCHAR(128) NOT NULL,
    text TEXT(30000) NOT NULL,
    userID BIGINT(44) NOT NULL,
    views BIGINT(44) DEFAULT 0 NOT NULL,
    upvotes BIGINT(44) DEFAULT 0 NOT NULL,
    downvotes BIGINT(44) DEFAULT 0 NOT NULL,
    datetime VARCHAR(256) NOT NULL
);