CREATE TABLE IF NOT EXISTS replies (
    replyID BIGINT(44) PRIMARY KEY AUTO_INCREMENT NOT NULL,
    byUserID BIGINT(44) NOT NULL,
    for_type VARCHAR(50) NOT NULL,
    forItemID BIGINT(44) NOT NULL,
    text VARCHAR(256) NOT NULL,
    datetime VARCHAR(256) NOT NULL
);